"""add v3 behavioral tables

Revision ID: c54e471c491c
Revises: 
Create Date: 2026-03-03 16:27:17.541252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54e471c491c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_regime_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regime', sa.String(length=30), nullable=True),
    sa.Column('risk_premium', sa.String(length=20), nullable=True),
    sa.Column('expected_forward_return', sa.String(length=20), nullable=True),
    sa.Column('risk_per_return', sa.String(length=20), nullable=True),
    sa.Column('valuation_ratio', sa.Float(), nullable=True),
    sa.Column('momentum', sa.String(length=20), nullable=True),
    sa.Column('vol_30d', sa.Float(), nullable=True),
    sa.Column('drawdown_from_peak', sa.Float(), nullable=True),
    sa.Column('nifty_current', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_regime_cache_id'), 'market_regime_cache', ['id'], unique=False)
    op.create_table('document_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('statement_from', sa.DateTime(), nullable=True),
    sa.Column('statement_to', sa.DateTime(), nullable=True),
    sa.Column('investor_name_in_doc', sa.String(length=255), nullable=True),
    sa.Column('investor_pan_in_doc', sa.String(length=20), nullable=True),
    sa.Column('total_folios', sa.Integer(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_uploads_id'), 'document_uploads', ['id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('median_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance_score', sa.Float(), nullable=True),
    sa.Column('risk_tolerance_sigma', sa.Float(), nullable=True),
    sa.Column('loss_aversion_lambda', sa.Float(), nullable=True),
    sa.Column('loss_aversion_sigma', sa.Float(), nullable=True),
    sa.Column('time_preference_k', sa.Float(), nullable=True),
    sa.Column('time_preference_sigma', sa.Float(), nullable=True),
    sa.Column('herding_index', sa.Float(), nullable=True),
    sa.Column('herding_sigma', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_table('investor_financial_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('income_source', sa.String(length=50), nullable=True),
    sa.Column('income_stability', sa.String(length=20), nullable=True),
    sa.Column('income_growth_expectation', sa.String(length=20), nullable=True),
    sa.Column('years_to_retirement', sa.Integer(), nullable=True),
    sa.Column('monthly_fixed_obligations', sa.Float(), nullable=True),
    sa.Column('annual_discretionary_spend', sa.Float(), nullable=True),
    sa.Column('upcoming_obligations_1y', sa.Float(), nullable=True),
    sa.Column('upcoming_obligations_3y', sa.Float(), nullable=True),
    sa.Column('upcoming_obligations_5y', sa.Float(), nullable=True),
    sa.Column('upcoming_obligations_10y', sa.Float(), nullable=True),
    sa.Column('obligation_notes', sa.Text(), nullable=True),
    sa.Column('existing_equity_mf', sa.Float(), nullable=True),
    sa.Column('existing_debt_mf', sa.Float(), nullable=True),
    sa.Column('existing_direct_equity', sa.Float(), nullable=True),
    sa.Column('existing_fixed_deposits', sa.Float(), nullable=True),
    sa.Column('existing_real_estate_value', sa.Float(), nullable=True),
    sa.Column('existing_gold', sa.Float(), nullable=True),
    sa.Column('existing_ppf_epf_nps', sa.Float(), nullable=True),
    sa.Column('existing_insurance_corpus', sa.Float(), nullable=True),
    sa.Column('existing_other_investments', sa.Float(), nullable=True),
    sa.Column('existing_cash_savings', sa.Float(), nullable=True),
    sa.Column('primary_residence_value', sa.Float(), nullable=True),
    sa.Column('total_investable_assets', sa.Float(), nullable=True),
    sa.Column('existing_liabilities', sa.Float(), nullable=True),
    sa.Column('net_worth', sa.Float(), nullable=True),
    sa.Column('has_experienced_real_loss', sa.Boolean(), nullable=True),
    sa.Column('worst_loss_amount', sa.Float(), nullable=True),
    sa.Column('worst_loss_context', sa.String(length=100), nullable=True),
    sa.Column('behavior_during_loss', sa.String(length=50), nullable=True),
    sa.Column('loss_recovery_experience', sa.String(length=50), nullable=True),
    sa.Column('target_return_annual_pct', sa.Float(), nullable=True),
    sa.Column('return_purpose', sa.Text(), nullable=True),
    sa.Column('time_horizon_years', sa.Integer(), nullable=True),
    sa.Column('is_aspiration_realistic', sa.Boolean(), nullable=True),
    sa.Column('aspiration_gap_notes', sa.Text(), nullable=True),
    sa.Column('decision_maker', sa.String(length=30), nullable=True),
    sa.Column('family_influence_level', sa.String(length=20), nullable=True),
    sa.Column('existing_advisor_relationship', sa.Boolean(), nullable=True),
    sa.Column('tax_bracket', sa.String(length=20), nullable=True),
    sa.Column('financial_capacity_score', sa.Float(), nullable=True),
    sa.Column('liquidity_runway_months', sa.Float(), nullable=True),
    sa.Column('obligation_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investor_id')
    )
    op.create_index(op.f('ix_investor_financial_context_id'), 'investor_financial_context', ['id'], unique=False)
    op.create_table('profile_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_history_id'), 'profile_history', ['id'], unique=False)
    op.create_table('transaction_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('upload_ids', sa.JSON(), nullable=True),
    sa.Column('disposition_effect', sa.Float(), nullable=True),
    sa.Column('disposition_sigma', sa.Float(), nullable=True),
    sa.Column('sip_discipline', sa.Float(), nullable=True),
    sa.Column('sip_sigma', sa.Float(), nullable=True),
    sa.Column('panic_score', sa.Float(), nullable=True),
    sa.Column('panic_sigma', sa.Float(), nullable=True),
    sa.Column('diversification', sa.Float(), nullable=True),
    sa.Column('diversification_sigma', sa.Float(), nullable=True),
    sa.Column('herding_score', sa.Float(), nullable=True),
    sa.Column('herding_sigma', sa.Float(), nullable=True),
    sa.Column('overtrading', sa.Float(), nullable=True),
    sa.Column('overtrading_sigma', sa.Float(), nullable=True),
    sa.Column('recency_bias', sa.Float(), nullable=True),
    sa.Column('recency_sigma', sa.Float(), nullable=True),
    sa.Column('n_transactions', sa.Integer(), nullable=True),
    sa.Column('date_range_months', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_scores_id'), 'transaction_scores', ['id'], unique=False)
    op.create_table('behavioral_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('data_sources', sa.String(length=50), nullable=True),
    sa.Column('last_game_session_id', sa.Integer(), nullable=True),
    sa.Column('last_assessment_id', sa.Integer(), nullable=True),
    sa.Column('last_transaction_score_id', sa.Integer(), nullable=True),
    sa.Column('loss_aversion', sa.Float(), nullable=True),
    sa.Column('loss_aversion_ci_lower', sa.Float(), nullable=True),
    sa.Column('loss_aversion_ci_upper', sa.Float(), nullable=True),
    sa.Column('horizon_tolerance', sa.Float(), nullable=True),
    sa.Column('horizon_tolerance_ci_lower', sa.Float(), nullable=True),
    sa.Column('horizon_tolerance_ci_upper', sa.Float(), nullable=True),
    sa.Column('liquidity_sensitivity', sa.Float(), nullable=True),
    sa.Column('behavioral_stability', sa.Float(), nullable=True),
    sa.Column('ambiguity_tolerance', sa.Float(), nullable=True),
    sa.Column('regret_sensitivity', sa.Float(), nullable=True),
    sa.Column('leverage_comfort', sa.Float(), nullable=True),
    sa.Column('goal_rigidity', sa.Float(), nullable=True),
    sa.Column('emotional_volatility', sa.Float(), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('composite_risk_score', sa.Float(), nullable=True),
    sa.Column('say_do_gap', sa.Float(), nullable=True),
    sa.Column('say_do_details', sa.JSON(), nullable=True),
    sa.Column('behavioral_flags', sa.JSON(), nullable=True),
    sa.Column('stress_prediction', sa.JSON(), nullable=True),
    sa.Column('drawdown_tolerance', sa.Float(), nullable=True),
    sa.Column('liquidity_buffer', sa.String(length=50), nullable=True),
    sa.Column('conversation_guide', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['last_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['last_game_session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['last_transaction_score_id'], ['transaction_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investor_id')
    )
    op.create_index(op.f('ix_behavioral_profiles_id'), 'behavioral_profiles', ['id'], unique=False)
    op.create_table('game_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=30), nullable=False),
    sa.Column('trial_number', sa.Integer(), nullable=False),
    sa.Column('stimulus', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_trials_id'), 'game_trials', ['id'], unique=False)
    op.create_table('parsed_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('balance_units', sa.Float(), nullable=True),
    sa.Column('scheme_name', sa.String(length=500), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('amfi_code', sa.String(length=20), nullable=True),
    sa.Column('folio_number', sa.String(length=50), nullable=True),
    sa.Column('amc_name', sa.String(length=255), nullable=True),
    sa.Column('scheme_category', sa.String(length=100), nullable=True),
    sa.Column('nifty_on_date', sa.Float(), nullable=True),
    sa.Column('nifty_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('scheme_nav_on_date', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['document_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_transactions_id'), 'parsed_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_transactions_id'), table_name='parsed_transactions')
    op.drop_table('parsed_transactions')
    op.drop_index(op.f('ix_game_trials_id'), table_name='game_trials')
    op.drop_table('game_trials')
    op.drop_index(op.f('ix_behavioral_profiles_id'), table_name='behavioral_profiles')
    op.drop_table('behavioral_profiles')
    op.drop_index(op.f('ix_transaction_scores_id'), table_name='transaction_scores')
    op.drop_table('transaction_scores')
    op.drop_index(op.f('ix_profile_history_id'), table_name='profile_history')
    op.drop_table('profile_history')
    op.drop_index(op.f('ix_investor_financial_context_id'), table_name='investor_financial_context')
    op.drop_table('investor_financial_context')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_document_uploads_id'), table_name='document_uploads')
    op.drop_table('document_uploads')
    op.drop_index(op.f('ix_market_regime_cache_id'), table_name='market_regime_cache')
    op.drop_table('market_regime_cache')
    # ### end Alembic commands ###
